// import { Geist, Geist_Mono, Akshar } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Raaz - Confession for you",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#0B192C]">{children}</body>
    </html>
  );
}
